add echo debug message

diff --git a/.github/workflows/c-cpp.yml b/.github/workflows/c-cpp.yml
--- a/.github/workflows/c-cpp.yml
+++ b/.github/workflows/c-cpp.yml
@@ -89,10 +89,8 @@ jobs:
         files: bld_/shadowsocks.${{ matrix.os }}.tar.bz2
 
     - name: send messages
-      id: mksd
-      if: success() || failure()
+      #if: success() || failure()
       run: |
-      #curl -SL --url "https://api.telegram.org/bot${{ secrets.API_TOKEN }}/sendmessage?chat_id=${{ secrets.CHAT_ID }}\&text=${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}"
-      #echo -e ${{ secrets.CHAT_ID }} >> $GITHUB_OUTPUT
-      echo -e "stat=success" >> $GITHUB_OUTPUT
+      echo -e "${{ secrets.CHAT_ID }}"
+      echo -e "stat=success"
 
